rustrun

diff --git a/rustrun b/rustrun
--- a/rustrun
+++ b/rustrun
@@ -1,7 +1,11 @@
 #! /usr/bin/env bash
 src_fn_str=$1
-exe_fn_str=$(echo $src_fn_str | sed -r 's/([^\.]+)\.rs/\1\.bin/g')
-#echo "@ps rsexec run as '$0 $1 $2 $3'"
-#echo "src exe $src_fn_str $exe_fn_str"
+bin_fn_str=$(echo $src_fn_str | sed -r 's/([^\.]+)\.rs/\1\.bin/g')
+bin_dir=$(mktemp -d -t bin-XXXXXXXXXX)
+#echo "@ps rustrun run as '$0 $1 $2 $3'"
+#echo "src exe $src_fn_str $bin_fn_str"
 
-rustc $src_fn_str -o $exe_fn_str && (./$exe_fn_str && rm $exe_fn_str) || echo "Errors while compile. Please check and fix errors above"
+target_fn_with_dir_str=$bin_dir/bin_fn_str
+rustc $src_fn_str -o $target_fn_with_dir_str && (./$($fn_with_dir_str  && rm $fn_with_dir_str) || echo "Errors while compile or exec. Please check and fix errors above"
+echo "Cleaning up $bin_dir"
+rm -rf $bin_dir
