almost done. rm debug code only left

diff --git a/rustrun b/rustrun
--- a/rustrun
+++ b/rustrun
@@ -1,18 +1,29 @@
 #! /usr/bin/env bash
 set -x
-src_absfn_str=$(realpath $1)
-src_basename_str=$(basename $src_absfn_str)
-projname_str=$(echo $src_basename_str | sed 's/\.rs//g')
+src_absfn_str=$(realpath "$1")
+src_basename_str=$(basename "$src_absfn_str")
+projname_str=$(echo "$src_basename_str" | sed 's/\.rs//g')
 tmpabsdn_str=$(mktemp -d -t rustrun_XXXXXXXXXXX)
-#echo $tmpabsdn_str
+echo "Tmp absdn: $tmpabsdn_str"
 #/data/data/com.termux/files/usr/tmp/runnerCy794qsVcqb
 # last test: rustrun_2Tv6am3YMI7
 projtmpabsdn_str=$tmpabsdn_str
 pushd $tmpabsdn_str
 cargo new $projname_str
+cn_ec_int=$?
+echo "Result code of cargo new in $(pwd) for $(projname_str) is $cn_ec_int"
+read _dummy
+if [ $cn_ec_int -ne 0 ]; then
+	echo "Failed to create project $projname_str in $tmpabsdn_str"
+	exit 1
+fi
+echo '@ps just after cargo new. press enter to cont'; read _dummy;
 projtmpabsdn_str=$tmpabsdn_str/$projname_str
-echo -e "\n[profile.dev]\nincremental = false" >> $projtmpabsdn_str/Cargo.toml
-cat $src_absfn_str | sed 's/^#!.*$//g' > $projtmpabsdn_str/src/main.rs
+echo -e "\n[profile.dev]\nincremental = false" >> "$projtmpabsdn_str/Cargo.toml"
+echo '@ps just after toml file addon. press enter to cont'; read -r _dummy;
+cat "$src_absfn_str" | sed 's/^#!.*$//g' > "$projtmpabsdn_str/src/main.rs"
+echo '@ps just after copy file. press enter to cont'; read -r _dummy;
 
-cd $projtmpabsdn_str
+
+cd "$projtmpabsdn_str" || exit 1
 cargo run
